# -*- coding: utf-8 -*-
"""Tank.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qEc4nwLKW-ljOjo1dUHWPHuVTpwvqLsV
"""

import pandas as pd

class Tank:
  def __init__(self, name = None):
    self.name = name

  @classmethod
  def water_index(self, idx, v, n):
    level, water_idx = 0, {}
    for i in range(n - 1):
      a = abs(idx[i] - idx[i + 1])
      if a > 1:
        for j in range(idx[i] + 1, idx[i + 1]):
          level = min(v[i], v[i + 1])
          water_idx[j] = level
    return water_idx

  @classmethod
  def tank_index(self, a):
    idx, v = [], []
    for i in range(len(a)):
      if a[i] > 0:
        idx.append(i)
        v.append(a[i])
    return (idx, v, len(idx))

  @classmethod
  def table(self, a, tank, water):
    df = pd.DataFrame()
    for k in range(len(a)):
      v = []
      if k in tank.keys():
        h = tank[k]
        v = ['E' for _ in range(max(a) - h)]
        for _ in range(h):
          v.append('T')
      elif k in water.keys():
        h = water[k]
        v = ['E' for _ in range(max(a) - h)]
        for _ in range(h):
          v.append('W')
      else:
        v = ['E' for _ in range(max(a))]
      df[k] = v
    return df

